2024-0308-01) 날짜자료형
 - 년, 월, 일, 시, 분, 초의 값을 보관
 - 덧셈과 뺄셈을 대상이 될 수 있음
 - 기본제공 함수로 SYSDATE, SYSTIMESTAMP 가 제공됨
 - DATE, TIMESTAMP(정교한 시간)
 
 1. DATE
  . 기본 날짜형
  (사용형식) 
   컬럼명 DATE
   
 사용 예시)
  CREATE TABLE TEMP06 (
    COL1 DATE,
    COL2 DATE );
 
 INSERT INTO TEMP06 VALUES(SYSDATE, SYSDATE-10);
 
 SELECT * FROM TEMP06;
 
 SELECT TO_CHAR(COL1,'YYYY-MM-DD HH24:MI:SS'),
        TO_CHAR(COL2,'YYYY-MM-DD HH24:MI:SS') 
    FROM TEMP06;
    

 INSERT INTO TEMP06 VALUES('20240308',SYSDATE+10);
 
 INSERT INTO TEMP06 VALUES('20240308',TO_DATE('20200308151650','YYYYMMDDHH24MISS'));
 
 2. TIMESTAMP
  - 10억분의 1초 단위의 정교한 시각 정보를 년 월일 정보와 함께 저장
  - 시간대(TIMEZONE)정보 저장
  - TIMESTAMP타입에 저장하는 날짜함수는 SYSTIMESTAMP임
  (사용 형식)
    컬럼명 TIMESTAMP  - 시간대 정보 저장하지 않음
    컬럼명 TIMESTAMP WITH LOCAL TIME ZONE  - 클라이언트가 위치한 시간대정보(TIMEZONE 타입과 동일) 
    컬럼명 TIMESTAMP WITH TIME ZONE  - 서버가 위치한 지역의 시간대 정보
 
  사용 예시)
  CREATE TABLE TEMP07(
    COL1 TIMESTAMP,
    COL2 TIMESTAMP WITH LOCAL TIME ZONE,
    COL3 TIMESTAMP WITH TIME ZONE );
    
 INSERT INTO TEMP07 VALUES (SYSDATE,SYSDATE,SYSDATE);
 INSERT INTO TEMP07 VALUES (SYSTIMESTAMP,SYSTIMESTAMP,SYSTIMESTAMP);
 
 SELECT * FROM TEMP07;
